### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by graforlock**
- Added two refs to my small choo-based projects.

### CODE REVIEW

**Review by YerkoPalma — COMMENTED** [review]
Are you sure you have a template for the choo-cli? the cli is pretty outdated

**Comment by graforlock** [comment]
You are right it should be under CLIs but not bound to it

**Comment by graforlock** [comment]
Updated now

**Review by YerkoPalma — APPROVED** [review]
LGTM

**Comment by YerkoPalma** [comment]
@graforlock merged. 
Any further help with this list would be awesome, there are some very outdated stuffs and choo development is always moving fast :)

**Pull request merged**
